artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kagglesdsdata/datasets/4458/8204/winequality-red.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20231201%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20231201T073226Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=614b924ccc73019c813712f51231d42e51264af230749a674791b229c444aec7d36e4bce0b792401e78d8bdd772a7337cfe474e111bd5dce23b96ec0fc59b0d8698052153f90b60173f7204e6c155609da92781254eb5b28a2ccd432373e1819ffdaeb70b991ebf0cc7c8e5f31de64558eb4807d63cf9bb4fb2bc1dfac1900bbc1f4f841efd16bed4f53b832803b2ad0d9e5bf6404d51df0b0ffb8aecfa0b29e116cb1d0b91f7605480de21769c429ccbf8fc2116b7c64828f4271a5aaa6e4109818bab420e9ed1fc59294ea7f2d7bdb7ab232242c608a4eda23e17332f69b4253cff8679f27d25f7db363fe74c004431ce4b4ae419f21504421e9ecc21c0ebe
  local_data_file: artifacts/data_ingestion/wineQuality-red.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wineQuality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wineQuality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json